# Copyright 2022-present, Lorenzo Bonicelli, Pietro Buzzega, Matteo Boschini, Angelo Porrello, Simone Calderara.
# All rights reserved.
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

best_args = {
    'seq-cifar10': {'sgd': {-1: {'lr': 0.1,
                                 'batch_size': 32,
                                 'n_epochs': 10}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10},
                           500: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10}},
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 10},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 10}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 10},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 10},}},
    'dream-seq-cifar10': {
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10,
                                 'val_dataset_size': 1000,
                                 'freezing_buff_size': 200},
                           500: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10,
                                 'val_dataset_size': 1000,
                                 'freezing_buff_size': 200}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 10,
                                    'val_dataset_size': 1000,
                                    'freezing_buff_size': 200},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 10,
                                    'val_dataset_size': 1000,
                                    'freezing_buff_size': 200},
                              },
                    'er_ace': {
                                    200: {'lr': 0.03,
                                        'optim_mom': 0,
                                        'optim_wd': 0,
                                        'val_dataset_size': 1000,
                                        'freezing_buff_size': 200,
                                        'batch_size': 32,
                                        'minibatch_size': 32,
                                        'n_epochs':10},
                                    500: {'lr': 0.03,
                                        'optim_mom': 0,
                                        'optim_wd': 0,
                                        'val_dataset_size': 1000,
                                        'freezing_buff_size': 200,
                                        'batch_size': 32,
                                        'minibatch_size': 32,
                                        'n_epochs':10}
                              }
                            },
    'seq-tinyimg': {'sgd': {-1: {'lr': 0.03,
                                 'batch_size': 32,
                                 'n_epochs': 10}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10},
                           500: {'lr': 0.03,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10},
                           5120: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 10}},
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'softmax_temp': 2.0,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 10},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 10}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 1.0,
                                    'batch_size': 32,
                                    'n_epochs': 10},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 10}}},
    'dream-seq-halftinyimg': {
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10,
                                 'val_dataset_size': 1000, 
                                 'freezing_buff_size': 200},
                           500: {'lr': 0.03,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10, 
                                 'val_dataset_size': 1000, 
                                 'freezing_buff_size': 200},
                           },
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'softmax_temp': 2.0,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 10,
                                  'val_dataset_size': 1000, 
                                  'freezing_buff_size': 200,}
                                  ,
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 10,
                                  'val_dataset_size': 1000, 
                                  'freezing_buff_size': 200}
                                  },
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 1.0,
                                    'batch_size': 32,
                                    'n_epochs':10,
                                    'val_dataset_size': 1000, 
                                    'freezing_buff_size': 200},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs':10,
                                    'val_dataset_size': 1000, 
                                    'freezing_buff_size': 200},
                              },
                    'er_ace': {
                                    500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 32, 'minibatch_size': 32, 'n_epochs':10},
                                    200: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 32, 'minibatch_size': 32, 'n_epochs':10},
                              }},
    'dream-seq-img100': {
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10},
                           1000: {'lr': 0.03,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 10},},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 8,
                                    'alpha': 0.1,
                                    'beta': 1.0,
                                    'batch_size': 8,
                                    'n_epochs':10,
                                    'val_dataset_size': 1000, 
                                    'freezing_buff_size': 200},
                              1000: {'lr': 0.03,
                                    'minibatch_size': 8,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 8,
                                    'n_epochs':10,
                                    'val_dataset_size': 1000, 
                                    'freezing_buff_size': 200}
                                    },
                    'er_ace': {
                                    200: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 8, 'minibatch_size': 8, 'n_epochs': 10},
                                    1000: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 8, 'minibatch_size': 8, 'n_epochs': 10}
                              }},
    'seq-cifar100': {
        'sgd': {-1: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0}},
        'er': {
            200: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0, 'n_epochs': 10},
            500: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0, 'n_epochs': 10}
        },
        
        'er_ace': {
            200: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'n_epochs': 10},
            500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'n_epochs': 10}
        },
        'derpp': {
            200: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5, 'n_epochs': 10},
            500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5, 'n_epochs': 10}
        }
    },
    'dream-seq-cifar100': {
        'er': {
            200: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0, 'n_epochs': 10, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 32, 'minibatch_size': 32},
            500: {'lr': 0.1, 'optim_mom': 0, 'optim_wd': 0, 'n_epochs': 10, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 32, 'minibatch_size': 32},
        },
        'er_ace': {
            200: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'n_epochs': 10, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 32, 'minibatch_size': 32},
            500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'n_epochs': 10, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 32, 'minibatch_size': 32},
        },
        'derpp': {
            200: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5, 'n_epochs': 10, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 32, 'minibatch_size': 32},
            500: {'lr': 0.03, 'optim_mom': 0, 'optim_wd': 0, 'alpha': 0.1, 'beta': 0.5, 'n_epochs': 10, 'val_dataset_size': 1000, 'freezing_buff_size': 200, 'batch_size': 32, 'minibatch_size': 32},    
        },
    }

}
